
image : docker:latest

stages:
  - build

build_job:
  stage: build
  script:
    - docker build -t TetrisAnt .
    - docker run --rm -v $CI_PROJECT_DIR::app TetrisAnt ant compile test-reports dist
  artifacts:
    paths:
      - Tetris.jar
      - test-reports	

    
