
image : docker:latest

services :
  - docker:dind
  
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  
before_script:
  - docker info

stages:
  - build

build_job:
  stage: build
  script:
    - docker build -t TetrisAnt .
    - docker run --rm -v $CI_PROJECT_DIR::app TetrisAnt ant compile test-reports dist
  artifacts:
    paths:
      - Tetris.jar
      - test-reports	

    
