
image : docker:latest

services :
  - docker:dind
  
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: ${DOCKER_HUB_USERNAME}/tetrisant:${CI_COMMIT_SHORT_SHA}
stages:
  - build
  - publishmanual

build_job:
  stage: build
  script:
    - echo "Image Name:${IMAGE_NAME}"
    - docker build -t ${IMAGE_NAME} .
    - docker images
  artifacts:
    paths:
      - Tetris.jar
      - test-reports	
      
publish_manual_job:
  stage: publishmanual
  script:
    - echo "Publishing application"
    - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker push ${IMAGE_NAME}
  when: manual
  only:
    - tags
    - master